// <auto-generated />
using HelloGraphQL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HelloGraphQL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210824191122_AddLinkGroupToDb")]
    partial class AddLinkGroupToDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HelloGraphQL.Models.LinkGroup", b =>
                {
                    b.Property<int>("LinkGroup_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LinkGroup_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkGroup_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LinkGroup_ID");

                    b.ToTable("LinkGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
